# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Accelerated Proximal Gradient method
#' @export
apg2 <- function(f, grad_f, prox_h, dim, max_it, eps, beta, accel) {
    .Call('_balancer_apg2', PACKAGE = 'balancer', f, grad_f, prox_h, dim, max_it, eps, beta, accel)
}

#' Accelerated proximal gradient method
#'
#' @param loss_ptr Pointer to loss function
#' @param grad_ptr Pointer to gradient function
#' @param prox_ptr Pointer to prox function
#' @param loss_opts List of options for loss (input data, tuning params, etc.)
#' @param dim Dimension
#' @param max_it Maximum number of iterations
#' @param eps Convergence tolerance
#' @param beta Backtracking line search parameter
#'
#' @return Optimal value
#' @export
apg <- function(grad_ptr, prox_ptr, loss_opts, prox_opts, dim, max_it, eps, alpha, beta, accel) {
    .Call('_balancer_apg', PACKAGE = 'balancer', grad_ptr, prox_ptr, loss_opts, prox_opts, dim, max_it, eps, alpha, beta, accel)
}

#' Accelerated Proximal Gradient method
#' @export
apg3 <- function(grad_f, prox_h, dim, max_it, eps, beta, accel, alpha) {
    .Call('_balancer_apg3', PACKAGE = 'balancer', grad_f, prox_h, dim, max_it, eps, beta, accel, alpha)
}

#' Loss function for linear link
NULL

#' Generic balancing loss function
balancing_loss <- function(theta, opts) {
    .Call('_balancer_balancing_loss', PACKAGE = 'balancer', theta, opts)
}

make_balancing_loss <- function() {
    .Call('_balancer_make_balancing_loss', PACKAGE = 'balancer')
}

#' Generic balancing loss gradient
balancing_grad <- function(theta, opts) {
    .Call('_balancer_balancing_grad', PACKAGE = 'balancer', theta, opts)
}

make_balancing_grad <- function() {
    .Call('_balancer_make_balancing_grad', PACKAGE = 'balancer')
}

#' Linear weights
lin_weights <- function(Xc, theta) {
    .Call('_balancer_lin_weights', PACKAGE = 'balancer', Xc, theta)
}

make_lin_weights <- function() {
    .Call('_balancer_make_lin_weights', PACKAGE = 'balancer')
}

#' normalized logit weights, numerically stable
softmax_weights <- function(Xc, theta) {
    .Call('_balancer_softmax_weights', PACKAGE = 'balancer', Xc, theta)
}

make_softmax_weights <- function() {
    .Call('_balancer_make_softmax_weights', PACKAGE = 'balancer')
}

make_no_prox <- function() {
    .Call('_balancer_make_no_prox', PACKAGE = 'balancer')
}

make_prox_l1 <- function() {
    .Call('_balancer_make_prox_l1', PACKAGE = 'balancer')
}

