# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Accelerated Proximal Gradient method
#' @export
apg2 <- function(f, grad_f, prox_h, dim, max_it, eps, beta, accel) {
    .Call('_balancer_apg2', PACKAGE = 'balancer', f, grad_f, prox_h, dim, max_it, eps, beta, accel)
}

#' Accelerated proximal gradient method
#'
#' @param loss_ptr Pointer to loss function
#' @param grad_ptr Pointer to gradient function
#' @param prox_ptr Pointer to prox function
#' @param loss_opts List of options for loss (input data, tuning params, etc.)
#' @param dim Dimension
#' @param max_it Maximum number of iterations
#' @param eps Convergence tolerance
#' @param beta Backtracking line search parameter
#'
#' @return Optimal value
#' @export
apg <- function(loss_ptr, grad_ptr, prox_ptr, loss_opts, dim, max_it, eps, beta) {
    .Call('_balancer_apg', PACKAGE = 'balancer', loss_ptr, grad_ptr, prox_ptr, loss_opts, dim, max_it, eps, beta)
}

#' Accelerated Proximal Gradient method
#' @export
apg3 <- function(grad_f, prox_h, dim, max_it, eps, beta, accel, alpha) {
    .Call('_balancer_apg3', PACKAGE = 'balancer', grad_f, prox_h, dim, max_it, eps, beta, accel, alpha)
}

#' Generic balancing loss gradient
NULL

#' Loss function for linear link
NULL

#' Linear weights
NULL

#' Generic balancing loss function
balancing_loss <- function(theta, opts) {
    .Call('_balancer_balancing_loss', PACKAGE = 'balancer', theta, opts)
}

make_balancing_loss <- function() {
    .Call('_balancer_make_balancing_loss', PACKAGE = 'balancer')
}

make_balancing_grad <- function() {
    .Call('_balancer_make_balancing_grad', PACKAGE = 'balancer')
}

no_prox <- function(theta, t) {
    .Call('_balancer_no_prox', PACKAGE = 'balancer', theta, t)
}

make_no_prox <- function() {
    .Call('_balancer_make_no_prox', PACKAGE = 'balancer')
}

prox_l1 <- function(x, lam) {
    .Call('_balancer_prox_l1', PACKAGE = 'balancer', x, lam)
}

make_prox_l1 <- function() {
    .Call('_balancer_make_prox_l1', PACKAGE = 'balancer')
}

